# Book settings
title: Predicting Indoor Flight Times With Python
author: Roie R. Black
copyright: "2022"
logo: images/logo/lpp.gif
email: roie.black@gmail.com

jupyter_execute_notebooks: force
exclude_patterns: [content/unpublished/*]
latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

html    :
  favicon: images/logo/lpp.ico
  baseurl: https://rblack42.github.io/nffs-2022-symposium-live
  home_page_in_navbar: true
  use_issues_button: true
  use_repository_button: true
  extra_navbar: Powered by <a href="https://jupyterbook.org">Jupyter Book</a>

repository:
  url: https://github.com/rblack42/nffs-2022-symposium-live
  path_to_book: docs
  branch: master

launch_buttons:
  notebook_interface: "classic"
  binderhub_url: "https://mybinder.ord"

binder:
  binderhub_url: https://mybinder.org
  text: "Launchbinder"

google_analytics:
  mytrackingcode: 'G-D3G7J2R7N3'

